package com.witcher.thewitcherrpg.feature_character_sheet.domain.item_types

enum class MagicType {
    NOVICE_SPELL,
    JOURNEYMAN_SPELL,
    MASTER_SPELL,
    NOVICE_DRUID_INVOCATION,
    JOURNEYMAN_DRUID_INVOCATION,
    MASTER_DRUID_INVOCATION,
    HIEROPHANT_FLAMINIKA_DRUID_INVOCATION,
    NOVICE_PREACHER_INVOCATION,
    JOURNEYMAN_PREACHER_INVOCATION,
    MASTER_PREACHER_INVOCATION,
    ARCH_PRIEST_INVOCATION,
    NOVICE_RITUAL,
    JOURNEYMAN_RITUAL,
    MASTER_RITUAL,
    HEX,
    BASIC_SIGN,
    ALTERNATE_SIGN,
    MINOR_GIFT,
    MAJOR_GIFT
}