package com.example.thewitcherrpg.feature_character_sheet.presentation.magic

enum class MagicType {
    NOVICE_SPELL,
    JOURNEYMAN_SPELL,
    MASTER_SPELL,
    NOVICE_DRUID_INVOCATION,
    JOURNEYMAN_DRUID_INVOCATION,
    MASTER_DRUID_INVOCATION,
    NOVICE_PREACHER_INVOCATION,
    JOURNEYMAN_PREACHER_INVOCATION,
    MASTER_PREACHER_INVOCATION,
    ARCH_PRIEST_INVOCATION,
    NOVICE_RITUAL,
    JOURNEYMAN_RITUAL,
    MASTER_RITUAL,
    HEX,
    BASIC_SIGN,
    ALTERNATE_SIGN
}